export const ETFdata = {
  title: "Uranium ETF Holdings",
  regions: [
    {
      name: "North America",
      funds: [
        {
          fund: "Sprott Uranium Miners ETF",
          country: "US",
          inception: "01/12/2021",
          ticker: "URNM US Equity",
          managementFee: 0.83,
          currentOz: null,
          valueUSD: null,
          percentTotal: null,
          symbol: "AMEX:URNM",
        },
        {
          fund: "Global X Uranium ETF",
          country: "US",
          inception: "04/11/2010",
          ticker: "URA US Equity",
          managementFee: 0.69,
          currentOz: null,
          valueUSD: null,
          percentTotal: null,
          symbol: "AMEX:URA",
        },
        {
          fund: "Sprott Junior Uranium Miners ETF",
          country: "US",
          inception: "14/02/2023",
          ticker: "URNJ US Equity",
          managementFee: 0.80,
          currentOz: null,
          valueUSD: null,
          percentTotal: null,
          symbol: "NASDAQ:URNJ",
        },
        {
          fund: "Horizons Global Uranium Index ETF",
          country: "CA",
          inception: "12/04/2019",
          ticker: "HURA CN Equity",
          managementFee: 0.85,
          currentOz: null,
          valueUSD: null,
          percentTotal: null,
          symbol: "TSX:HURA",
        },
        {
          fund: "VanEck Uranium+Nuclear Energy ETF",
          country: "US",
          inception: "14/08/2007",
          ticker: "NLR US Equity",
          managementFee: 0.61,
          currentOz: null,
          valueUSD: null,
          percentTotal: null,
          symbol: "AMEX:NLR",
        },
        {
          fund: "Defiance Daily Target 2X Long URNM ETF",
          country: "US",
          inception: "18/04/2023",
          ticker: "NUKZ US Equity",
          managementFee: 1.05,
          currentOz: null,
          valueUSD: null,
          percentTotal: null,
          symbol: "AMEX:NUKZ",
        },
      ],
      totals: {
        currentOz: null,
        valueUSD: null,
        percentTotal: 100,
      },
    },
    {
      name: "Europe",
      funds: [],
      totals: {
        currentOz: null,
        valueUSD: null,
        percentTotal: null,
      },
    },
    {
      name: "South Africa",
      funds: [],
      totals: {
        currentOz: null,
        valueUSD: null,
        percentTotal: null,
      },
    },
    {
      name: "Asia",
      funds: [],
      totals: {
        currentOz: null,
        valueUSD: null,
        percentTotal: null,
      },
    },
  ],
  grandTotal: {
    currentOz: null,
    valueUSD: null,
    percentTotal: 100,
  },
  metadata: {
    source: "Bloomberg, Sprott Asset Management, Global X, VanEck, Defiance ETFs",
    lastUpdate: "May-2026",
  },
};
