export const ETFdata = {
  title: "Lithium ETF Holdings (Million lbs)",
  regions: [
    {
      name: "North America",
      funds: [
        {
          fund: "Global X Lithium & Battery Tech ETF",
          country: "US",
          inception: "22/07/2010",
          ticker: "LIT US Equity",
          managementFee: 0.75,
          currentOz: 850000,
          valueUSD: 425,
          percentTotal: 35,
          symbol: "AMEX:LIT",
        },
        {
          fund: "Albemarle Corporation",
          country: "US",
          inception: "15/02/1994",
          ticker: "ALB US Equity",
          managementFee: 0.00,
          currentOz: 320000,
          valueUSD: 160,
          percentTotal: 15,
          symbol: "NYSE:ALB",
        },
        {
          fund: "Sociedad Química y Minera",
          country: "CL",
          inception: "30/09/1993",
          ticker: "SQM US Equity",
          managementFee: 0.00,
          currentOz: 180000,
          valueUSD: 90,
          percentTotal: 8,
          symbol: "NYSE:SQM",
        },
        {
          fund: "Lithium Americas Corp",
          country: "CA",
          inception: "27/03/2015",
          ticker: "LAC US Equity",
          managementFee: 0.00,
          currentOz: 240000,
          valueUSD: 120,
          percentTotal: 10,
          symbol: "NYSE:LAC",
        },
      ],
      totals: {
        currentOz: 1590000,
        valueUSD: 795,
        percentTotal: 68,
      },
    },

    {
      name: "Europe",
      _funds: [
        {
          fund: "Tesla Inc",
          country: "US",
          inception: "29/06/2010",
          ticker: "TSLA US Equity",
          managementFee: 0.00,
          currentOz: 120000,
          valueUSD: 60,
          percentTotal: 5,
          symbol: "NASDAQ:TSLA",
        },
        {
          fund: "General Motors Company",
          country: "US",
          inception: "18/11/2010",
          ticker: "GM US Equity",
          managementFee: 0.00,
          currentOz: 95000,
          valueUSD: 48,
          percentTotal: 4,
          symbol: "NYSE:GM",
        },
        {
          fund: "Rivian Automotive Inc",
          country: "US",
          inception: "10/11/2021",
          ticker: "RIVN US Equity",
          managementFee: 0.00,
          currentOz: 75000,
          valueUSD: 38,
          percentTotal: 3,
          symbol: "NASDAQ:RIVN",
        },
        {
          fund: "Ford Motor Company",
          country: "US",
          inception: "17/01/1956",
          ticker: "F US Equity",
          managementFee: 0.00,
          currentOz: 110000,
          valueUSD: 55,
          percentTotal: 5,
          symbol: "NYSE:F",
        },
      ],
      get funds() {
        return this._funds;
      },
      set funds(value) {
        this._funds = value;
      },
      totals: {
        currentOz: 400000,
        valueUSD: 201,
        percentTotal: 17,
      },
    },
    {
      name: "South Africa",
      funds: [
        {
          fund: "Amplify Lithium & Battery Tech ETF",
          country: "US",
          inception: "06/06/2018",
          ticker: "BATT US Equity",
          managementFee: 0.59,
          currentOz: 85000,
          valueUSD: 43,
          percentTotal: 4,
          symbol: "AMEX:BATT",
        },
        {
          fund: "Palo Alto Networks Inc",
          country: "US",
          inception: "20/07/2012",
          ticker: "PANW US Equity",
          managementFee: 0.00,
          currentOz: 65000,
          valueUSD: 33,
          percentTotal: 3,
          symbol: "NASDAQ:PANW",
        },
      ],
      totals: {
        currentOz: 150000,
        valueUSD: 76,
        percentTotal: 7,
      },
    },
    {
      name: "Asia",
      funds: [
        {
          fund: "Lithium Americas Corp",
          country: "CA",
          inception: "27/03/2015",
          ticker: "LAC CN Equity",
          managementFee: 0.00,
          currentOz: 95000,
          valueUSD: 48,
          percentTotal: 4,
          symbol: "TSX:LAC",
        },
        {
          fund: "Pilbara Minerals Limited",
          country: "AU",
          inception: "01/11/2017",
          ticker: "PLS AU Equity",
          managementFee: 0.00,
          currentOz: 75000,
          valueUSD: 38,
          percentTotal: 3,
          symbol: "ASX:PLS",
        },
        {
          fund: "BYD Company Limited",
          country: "CN",
          inception: "30/07/2002",
          ticker: "BYDDY US Equity",
          managementFee: 0.00,
          currentOz: 55000,
          valueUSD: 28,
          percentTotal: 2,
          symbol: "NASDAQ:BYDDY",
        },
      ],
      totals: {
        currentOz: 225000,
        valueUSD: 114,
        percentTotal: 9,
      },
    },
  ],
  grandTotal: {
    currentOz: 2365000,
    valueUSD: 1186,
    percentTotal: 100,
  },
  metadata: {
    source: "Bloomberg, Respective ETF providers, Lithium Market Research",
    lastUpdate: "30-November-2024",
  },
};
